/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.projek.keuangan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dira
 */
public class TransaksiForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransaksiForm.class.getName());
    DefaultTableModel model;

    /**
     * Creates new form TransaksiForm
     */
    public TransaksiForm() {
        initComponents();
        datePicker1.setDateToToday();
        datePicker1.getSettings().setAllowKeyboardEditing(false);

    // Pastikan urutan kolom ini (Total 6 Kolom)
        Object[] kolom = {"ID", "Tanggal", "Jenis", "Event", "Nominal", "Keterangan"};
        model = new DefaultTableModel(kolom, 0);
        tblTransaksi.setModel(model);

        loadData();
    }
    
    private void loadData() {
    model.setRowCount(0); 
    try {
        Connection conn = Koneksi.sambung();
        Statement st = conn.createStatement();
        // Mengurutkan berdasarkan ID terbaru agar transaksi terakhir ada di atas
        String sql = "SELECT * FROM transaksi ORDER BY id_transaksi DESC";
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_transaksi"),      // Kolom 0
                rs.getString("tgl_transaksi"),  // Kolom 1
                rs.getString("jenis_transaksi"),// Kolom 2
                rs.getString("event"),          // Kolom 3
                rs.getDouble("nominal"),        // Kolom 4
                rs.getString("keterangan")      // Kolom 5
            });
        }
        hitungUlangSaldo();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNominal = new javax.swing.JTextField();
        txtKeterangan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        cbJenis = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        lblBalance = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        cbEvent = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNominalKeyReleased(evt);
            }
        });

        jLabel1.setText("Nominal");

        jLabel2.setText("Keterangan");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));
        cbJenis.addActionListener(this::cbJenisActionPerformed);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Jenis Transaksi", "Event", "Nominal", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(tblTransaksi);

        lblBalance.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        cbEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepengurusan", "Seminar & Workshop", "Business Sharing", "EXPO", "Other" }));
        cbEvent.addActionListener(this::cbEventActionPerformed);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("PENCATATAN TRANSAKSI KEUANGAN UKM");

        jLabel4.setText("Jenis Transaksi");

        jLabel5.setText("Event");

        jLabel6.setText("Tanggal Transaksi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSimpan)
                            .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(cbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addComponent(btnSimpan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
        String tgl = datePicker1.getDateStringOrEmptyString();
        String jns = cbJenis.getSelectedItem().toString();
        String evtName = cbEvent.getSelectedItem().toString();
        String ket = txtKeterangan.getText();
        String nomClean = txtNominal.getText().replaceAll("\\.", "");

        if (tgl.isEmpty() || nomClean.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal dan Nominal wajib diisi!");
            return;
        }

        double nom = Double.parseDouble(nomClean);

        Connection conn = Koneksi.sambung();
        // ID tidak dimasukkan karena AUTO_INCREMENT
        String sql = "INSERT INTO transaksi (tgl_transaksi, jenis_transaksi, event, nominal, keterangan) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        
        pst.setString(1, tgl);
        pst.setString(2, jns);
        pst.setString(3, evtName);
        pst.setDouble(4, nom);
        pst.setString(5, ket);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan!");

        loadData(); // Memanggil ulang data agar ID muncul di tabel
        
        // Reset Form
        txtKeterangan.setText("");
        txtNominal.setText("");
        datePicker1.setDateToToday();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Simpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNominalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNominalKeyReleased
        try {
        // 1. Ambil teks, hapus semua titik yang ada agar bisa dihitung ulang
        String originalText = txtNominal.getText().replaceAll("\\.", "");
        if (originalText.isEmpty()) return;

        // 2. Ubah ke angka
        double nominal = Double.parseDouble(originalText);

        // 3. Format ulang dengan titik pemisah ribuan (Format Indonesia)
        String formattedText = String.format("%,.0f", nominal).replace(',', '.');

        // 4. Set kembali ke textfield
        txtNominal.setText(formattedText);
        
    } catch (NumberFormatException e) {
        // Abaikan jika bukan angka
    }
    }//GEN-LAST:event_txtNominalKeyReleased

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisActionPerformed

    private void cbEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventActionPerformed
    private void hitungUlangSaldo() {
    double totalPemasukan = 0;
    double totalPengeluaran = 0;

    for (int i = 0; i < model.getRowCount(); i++) {
        try {
            // Ambil data Jenis (Index 2)
            String jenis = model.getValueAt(i, 2).toString();
            
            // Ambil data Nominal (Index 4), hapus titik jika ada agar bisa diparse
            String nomString = model.getValueAt(i, 4).toString().replace(".", "");
            double nominal = Double.parseDouble(nomString);

            if (jenis.equalsIgnoreCase("Pemasukan")) {
                totalPemasukan += nominal;
            } else {
                totalPengeluaran += nominal;
            }
        } catch (Exception e) {
            // Lewati jika ada baris yang error/kosong
            System.out.println("Error hitung baris ke-" + i + ": " + e.getMessage());
        }
    }

    double saldoAkhir = totalPemasukan - totalPengeluaran;
    
    // Format tampilan ke Rupiah dengan titik
    String formatted = String.format("%,.0f", saldoAkhir).replace(',', '.');
    lblBalance.setText("Rp " + formatted);
    
    // Ubah warna teks (Merah jika minus, Hijau jika surplus)
    lblBalance.setForeground(saldoAkhir < 0 ? java.awt.Color.RED : new java.awt.Color(0, 153, 51));
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransaksiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbEvent;
    private javax.swing.JComboBox<String> cbJenis;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}