/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.transaksiController;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Model.Transaksi;
import util.Session;

/**
 *
 * @author dira
 */
public class transaksiForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transaksiForm.class.getName());
    DefaultTableModel model;
    private int selectedTransaksiId = -1;
    
    public transaksiForm() { 
        initComponents();
        transaksiController tc = new transaksiController();
        
        model = (DefaultTableModel)
        tblTransaksi.getModel(); 
        tc.loadData(model); 
        Date();
        model.addTableModelListener(e -> hitungUlangSaldo());
        hitungUlangSaldo();
    }

    /**
     * Creates new form TransaksiForm
     */
    private void Date() {
        for (int i = 1; i <= 31; i++) {
            cbTgl.addItem(String.valueOf(i));
        }

        // Bulan 1–12
        String[] bulan = {"01","02","03","04","05","06","07","08","09","10","11","12"};
        for (String b : bulan) {
            cbBln.addItem(b);
        }

        // Tahun 2020–2030
        for (int i = 2020; i <= 2030; i++) {
            cbThn.addItem(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNominal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        cbJenis = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        cbEvent = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbTgl = new javax.swing.JComboBox<>();
        cbBln = new javax.swing.JComboBox<>();
        cbThn = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        lblSaldo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNominal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNominalKeyReleased(evt);
            }
        });

        jLabel1.setText("Nominal");

        jLabel2.setText("Keterangan");

        btnSimpan.setBackground(new java.awt.Color(102, 102, 255));
        btnSimpan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        cbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemasukan", "Pengeluaran" }));
        cbJenis.addActionListener(this::cbJenisActionPerformed);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Jenis Transaksi", "Event", "Nominal", "Keterangan"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblTransaksi);

        cbEvent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepengurusan", "Seminar & Workshop", "Business Sharing", "EXPO", "Other" }));
        cbEvent.addActionListener(this::cbEventActionPerformed);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("PENCATATAN TRANSAKSI KEUANGAN UKM");

        jLabel4.setText("Jenis Transaksi");

        jLabel5.setText("Event");

        jLabel6.setText("Tanggal Transaksi:");

        jLabel7.setText("Bulan:");

        jLabel8.setText("Tahun:");

        txtKet.setColumns(20);
        txtKet.setRows(5);
        jScrollPane3.setViewportView(txtKet);

        lblSaldo.setForeground(new java.awt.Color(0, 204, 0));

        jLabel9.setText("Saldo:");

        btnEdit.setBackground(new java.awt.Color(255, 153, 0));
        btnEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(117, 117, 117))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(169, 169, 169)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(cbEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbThn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:                                        
    try {
        // Ambil nominal dari textfield, hapus titik ribuan dulu
        String rawNominal = txtNominal.getText().replaceAll("\\.", "");
        double nominal = Double.parseDouble(rawNominal);

        String keterangan = txtKet.getText();
        String jenis = cbJenis.getSelectedItem().toString();
        String event = cbEvent.getSelectedItem().toString();
        String day = cbTgl.getSelectedItem().toString();
        String month = cbBln.getSelectedItem().toString();
        String year = cbThn.getSelectedItem().toString();

        // Gabungkan jadi format yyyy-MM-dd
        String tanggalStr = year + "-" + month + "-" + String.format("%02d", Integer.parseInt(day));
        java.sql.Date tanggalSql = java.sql.Date.valueOf(tanggalStr);

        // Buat objek Transaksi
        Transaksi t = new Transaksi(1, tanggalSql, jenis, event, nominal, keterangan);

        // Simpan via controller
        transaksiController tc = new transaksiController();
        if (tc.tambahTransaksi(t)) {
            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            tc.loadData(model); // refresh JTable
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNominalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNominalKeyReleased
        // TODO add your handling code here:                                        
    try {
        // Ambil teks, hapus titik ribuan
        String originalText = txtNominal.getText().replaceAll("\\.", "");
        if (originalText.isEmpty()) return;

        // Ubah ke angka
        double nominal = Double.parseDouble(originalText);

        // Format ulang dengan titik ribuan (Indonesia style)
        String formattedText = String.format("%,d", (long) nominal).replace(',', '.');

        // Set kembali ke textfield
        txtNominal.setText(formattedText);

    } catch (NumberFormatException e) {
        // Abaikan jika bukan angka
    }

    }//GEN-LAST:event_txtNominalKeyReleased

    private void cbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbJenisActionPerformed

    private void cbEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEventActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:                                      
        if (selectedTransaksiId > 0) {
            try {
                String rawNominal = txtNominal.getText().replace(",", "");
                double nominal = Double.parseDouble(rawNominal);
                String keterangan = txtKet.getText();
                String jenis = cbJenis.getSelectedItem().toString();
                String event = cbEvent.getSelectedItem().toString();
                String day = cbTgl.getSelectedItem().toString();
                String month = cbBln.getSelectedItem().toString();
                String year = cbThn.getSelectedItem().toString();

                String tanggalStr = year + "-" + month + "-" + String.format("%02d", Integer.parseInt(day));
                java.sql.Date tanggalSql = java.sql.Date.valueOf(tanggalStr);

                Transaksi t = new Transaksi(selectedTransaksiId, tanggalSql, jenis, event, nominal, keterangan, Session.userId);
                
                transaksiController tc = new transaksiController();
                if (tc.editTransaksi(t)) {
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil diupdate!");
                    tc.loadData(model);
                    hitungUlangSaldo();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal update transaksi.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris transaksi dulu!");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:                                         
        int row = tblTransaksi.getSelectedRow();
        if (row >= 0) {
            // Ambil data dari tabel
            selectedTransaksiId = (int) model.getValueAt(row, 0); // kolom 0 = transaksi_id
            String tanggal = model.getValueAt(row, 1).toString();
            String jenis = model.getValueAt(row, 2).toString();
            String event = model.getValueAt(row, 3).toString();
            String nominal = model.getValueAt(row, 4).toString();
            String ket = model.getValueAt(row, 5).toString();

            // Set ke form
            txtNominal.setText(nominal);
            txtKet.setText(ket);
            cbJenis.setSelectedItem(jenis);
            cbEvent.setSelectedItem(event);

            // Pecah tanggal yyyy-MM-dd ke cbTgl, cbBln, cbThn
            String[] parts = tanggal.split("-");
            cbThn.setSelectedItem(parts[0]);
            cbBln.setSelectedItem(parts[1]);
            cbTgl.setSelectedItem(parts[2]);
        }
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new View.dashForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void hitungUlangSaldo() {
        double totalPemasukan = 0;
        double totalPengeluaran = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                String jenis = model.getValueAt(i, 2).toString(); // kolom 2 = Jenis Transaksi
                Object value = model.getValueAt(i, 4);            // kolom 4 = Nominal

                double nominal;
                if (value instanceof Number) {
                    nominal = ((Number) value).doubleValue();
                } else {
                    nominal = Double.parseDouble(value.toString().replace(".", ""));
                }

                if (jenis.equalsIgnoreCase("Pemasukan")) {
                    totalPemasukan += nominal;
                } else {
                    totalPengeluaran += nominal;
                }
            } catch (Exception e) {
                System.out.println("Error hitung baris ke-" + i + ": " + e.getMessage());
            }
        }

        double saldoAkhir = totalPemasukan - totalPengeluaran;
        String formatted = String.format("%,.0f", saldoAkhir).replace(',', '.');
        lblSaldo.setText("Rp " + formatted);
        lblSaldo.setForeground(saldoAkhir < 0 ? java.awt.Color.RED : new java.awt.Color(0, 153, 51));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transaksiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbBln;
    private javax.swing.JComboBox<String> cbEvent;
    private javax.swing.JComboBox<String> cbJenis;
    private javax.swing.JComboBox<String> cbTgl;
    private javax.swing.JComboBox<String> cbThn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}